/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/drone.glb -o components/DroneModel.tsx 
Author: Vaptor-Studio (https://sketchfab.com/VapTor)
Created: Thu Feb  3 09:05:02 2022
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/models/cf3ed83c1b87486d90435f54c074e16e
Title: S9 Mini Drone
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { useFrame } from '@react-three/fiber'

type ActionName = 'Take 01'

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName
}

type GLTFResult = GLTF & {
  nodes: {
    Circle_0: THREE.Mesh
    Circle_1: THREE.Mesh
    Circle001_0: THREE.Mesh
    Circle001_1: THREE.Mesh
    Cube_0: THREE.Mesh
    Cube_1: THREE.Mesh
    Sphere_0: THREE.Mesh
    Sphere001_0: THREE.Mesh
    Cube001_0: THREE.Mesh
    Circle002_0: THREE.Mesh
    Circle003_0: THREE.Mesh
    Circle004_0: THREE.Mesh
    Circle005_0: THREE.Mesh
    Cylinder_0: THREE.Mesh
    Cylinder001_0: THREE.Mesh
    Circle006_0: THREE.Mesh
  }
  materials: {
    ['Material.001']: THREE.MeshStandardMaterial
    ['Material.003']: THREE.MeshStandardMaterial
    ['Material.002']: THREE.MeshStandardMaterial
    ['Material.005']: THREE.MeshStandardMaterial
    ['Material.004']: THREE.MeshStandardMaterial
    ['Cylinder.001_0']: THREE.MeshStandardMaterial
    pale: THREE.MeshStandardMaterial
    ['Material.006']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export const Model = React.forwardRef<THREE.Group, JSX.IntrinsicElements['group']>((props, ref) => {
  const localRef = useRef<THREE.Group>(null)
  // Merge forwarded ref with local ref
  React.useImperativeHandle(ref, () => localRef.current as THREE.Group)

  const { nodes, animations } = useGLTF('/drone.glb') as GLTFResult
  const { actions } = useAnimations(animations, localRef)

  // Propeller Refs
  const prop1 = useRef<THREE.Group>(null)
  const prop2 = useRef<THREE.Group>(null)
  const prop3 = useRef<THREE.Group>(null)
  const prop4 = useRef<THREE.Group>(null)

  useFrame((state, delta) => {
    // Spin propellers fast
    const speed = 40 * delta;
    if (prop1.current) prop1.current.rotation.z -= speed;
    if (prop2.current) prop2.current.rotation.z += speed;
    if (prop3.current) prop3.current.rotation.z -= speed;
    if (prop4.current) prop4.current.rotation.z += speed;
  })

  // Clean, High-End Professional Engineering Materials
  const stealthBodyMaterial = new THREE.MeshPhysicalMaterial({
    color: new THREE.Color("#e0e2e5"), // Apple-like Silver
    metalness: 0.7,
    roughness: 0.2,
    clearcoat: 1.0,
    clearcoatRoughness: 0.1,
  });

  const stealthDetailMaterial = new THREE.MeshPhysicalMaterial({
    color: new THREE.Color("#2a2c30"), // Space Gray
    metalness: 0.9,
    roughness: 0.4,
  });

  const glowingCyanMaterial = new THREE.MeshStandardMaterial({
    color: new THREE.Color("#00f2ff"),
    emissive: new THREE.Color("#00f2ff"),
    emissiveIntensity: 1.5, // Toned down since there's no bloom
    toneMapped: false,
  });

  const glowingBlueMaterial = new THREE.MeshStandardMaterial({
    color: new THREE.Color("#0066ff"),
    emissive: new THREE.Color("#0066ff"),
    emissiveIntensity: 1.5,
    toneMapped: false,
  });

  const propellerMaterial = new THREE.MeshPhysicalMaterial({
    color: new THREE.Color("#111111"),
    metalness: 0.8,
    roughness: 0.3,
    transparent: true,
    opacity: 0.5,
  });

  return (
    <group ref={localRef} {...props} dispose={null}>
      <group name="OSG_Scene">
        <group name="RootNode_(gltf_orientation_matrix)" rotation={[-Math.PI / 2, 0, 0]} scale={0.1}>
          <group name="RootNode_(model_correction_matrix)">
            <group name="Root">
              {/* Main Body Parts */}
              <group name="Circle" position={[1.378, 1.984, 0.607]} scale={0.421}>
                <mesh name="Circle_0" geometry={nodes.Circle_0.geometry} material={stealthBodyMaterial} />
                <mesh name="Circle_1" geometry={nodes.Circle_1.geometry} material={stealthDetailMaterial} />
              </group>
              <group name="Circle001" position={[3.077, 2.731, -0.052]}>
                <mesh name="Circle001_0" geometry={nodes.Circle001_0.geometry} material={stealthBodyMaterial} />
                <mesh name="Circle001_1" geometry={nodes.Circle001_1.geometry} material={glowingCyanMaterial} />
              </group>
              <group name="Cube" position={[0.016, 0.269, 0]} scale={[1.181, 1, 1]}>
                <mesh name="Cube_0" geometry={nodes.Cube_0.geometry} material={stealthBodyMaterial} />
                <mesh name="Cube_1" geometry={nodes.Cube_1.geometry} material={glowingBlueMaterial} />
              </group>
              
              {/* Spheres (Lenses/Sensors) */}
              <group name="Sphere" position={[0.048, 2.873, -0.188]} scale={[0.096, 0.096, 0.121]}>
                <mesh name="Sphere_0" geometry={nodes.Sphere_0.geometry} material={glowingCyanMaterial} />
              </group>
              <group name="Sphere001" position={[-0.002, -2.487, -0.124]} scale={[0.174, 0.13, 0.163]}>
                <mesh name="Sphere001_0" geometry={nodes.Sphere001_0.geometry} material={glowingBlueMaterial} />
              </group>
              
              <group name="Cube001" position={[1.136, 0.834, 0.278]} scale={[0.101, 0.05, 0.05]}>
                <mesh name="Cube001_0" geometry={nodes.Cube001_0.geometry} material={stealthDetailMaterial} />
              </group>
              
              {/* Propellers */}
              <group ref={prop1} name="Circle002" position={[3.059, 2.733, 1.004]} rotation={[0, 0, 0.052]} scale={0.147}>
                <mesh name="Circle002_0" geometry={nodes.Circle002_0.geometry} material={propellerMaterial} />
              </group>
              <group ref={prop2} name="Circle003" position={[-3.035, 2.754, 1.004]} rotation={[0, 0, -1.435]} scale={0.147}>
                <mesh name="Circle003_0" geometry={nodes.Circle003_0.geometry} material={propellerMaterial} />
              </group>
              <group ref={prop3} name="Circle004" position={[-3.035, -2.19, 1.004]} rotation={[0, 0, -0.391]} scale={0.147}>
                <mesh name="Circle004_0" geometry={nodes.Circle004_0.geometry} material={propellerMaterial} />
              </group>
              <group ref={prop4} name="Circle005" position={[3.047, -2.187, 1.004]} rotation={[0, 0, -1.36]} scale={0.147}>
                <mesh name="Circle005_0" geometry={nodes.Circle005_0.geometry} material={propellerMaterial} />
              </group>

              {/* Cylinders (Motors) */}
              <group name="Cylinder" position={[0.057, 3.094, 0.252]} rotation={[Math.PI / 2, 0, 0]} scale={0.122}>
                <mesh name="Cylinder_0" geometry={nodes.Cylinder_0.geometry} material={stealthDetailMaterial} />
              </group>
              <group name="Cylinder001" position={[-0.06, 3.094, 0.252]} rotation={[Math.PI / 2, 0, 0]} scale={0.122}>
                <mesh name="Cylinder001_0" geometry={nodes.Cylinder001_0.geometry} material={stealthDetailMaterial} />
              </group>
              
              <group name="Circle006" position={[0.003, 0.457, -4.295]} scale={12.303}>
                <mesh name="Circle006_0" geometry={nodes.Circle006_0.geometry} visible={false} />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
})

useGLTF.preload('/drone.glb')
